### ISSUE TITLE
Is it possible to exclude the `<|eot_id|>` token?

### ISSUE THREAD

**Issue by JanWerder** [Adriankhl/godot-llm#10]
I know there are already some options for llama.cpp to exclude some tokens, but currently facing the `<|eot_id|>` with Llama3 Instruct in `Interactive` mode.

My options look like this:
![image](https://github.com/Adriankhl/godot-llm/assets/596986/66691ad9-0904-45b4-867d-ae7f6d2c777a)

But I'm getting the `<|eot_id|>` token. (should_output_eos has no effect)

![image](https://github.com/Adriankhl/godot-llm/assets/596986/20f1db60-a3f7-42de-a28f-348e0c59fd88)

I could do some string filtering, but before I set up a complicated system of string caching and live-detection, I thought I'd ask.

**Comment by Adriankhl** [comment]
I have tested on my side and it definitely works here. Could you download the new `Godot LLM Template`, either from the asset library or from [here](https://github.com/Adriankhl/godot-llm-template), then open the application -> Text Generation -> Change `None` to `Person` -> Generate, then see if <|eot_id|> is there or not

**Comment by Adriankhl** [comment]
It can also well be this issue: https://github.com/ggerganov/llama.cpp/issues/6772
so the problem can come from the model side, but I think it has already been fixed
If the issue persists, could you try one of the "fixed" model [here](https://huggingface.co/NikolayKozloff/Meta-Llama-3-8B-Instruct-bf16-correct-pre-tokenizer-and-EOS-token-Q8_0-Q6_k-Q4_K_M-GGUF/tree/main)

**Comment by JanWerder** [comment]
You're right, it was a model issue. The model you linked fixed the issue.
What's weird is, that I used the linked `Meta-Llama-3-8B-Instruct-Q5_K_M.gguf` from the ReadMe.
So on the one hand, I would think that it's best to change it, but on the other hand you didn't have the issue with the same model.

**Comment by Adriankhl** [comment]
It can well be we downloaded different versions of the model from the same repo, I have added a FAQ section in the README to point out that model versions can be a problem even if the model is the same
