### ISSUE TITLE
Documentation for JSON schemas

### ISSUE THREAD

**Issue by Inotist** [Adriankhl/godot-llm#16]
I've managed to figure out some of the different types and properties that can be used in a JSON schema, but whenever I try to find some documentation about this tool, I find nothing, not even related to llama.cpp

Maybe I'm just very bad at searching, but is there any documentation regarding this tool? I find it incredibly useful and powerfull, but it is a handicap not having a proper documentation on the correct syntax, available properties and available types...

Btw thanks a lot for this library, it is amazing!

**Comment by JekSun97** [comment]
I also searched for this information, but didn't find anything #7

**Comment by Adriankhl** [comment]
It uses a subset of schema which is documented [here](https://json-schema.org/). 

I agree that the documentation is not clear on llama.cpp. I also need to dive into the source code of llama.cpp to figure out how to use Json schema in my example. You are welcome to ask any question here though. I believe it will be clearer once we have multiple practical examples.

**Comment by Inotist** [comment]
> It uses a subset of schema which is documented [here](https://json-schema.org/).
> 
> I agree that the documentation is not clear on llama.cpp. I also need to dive into the source code of llama.cpp to figure out how to use Json schema in my example. You are welcome to ask any question here though. I believe it will be clearer once we have multiple practical examples.

Thanks a lot! That's exactly what I was looking for, concretely the page https://json-schema.org/understanding-json-schema/reference/type is going to be super useful.
