### ISSUE TITLE
Cannot Install - Crash v4.2.1

### ISSUE THREAD

**Issue by Mixddux** [Adriankhl/godot-llm#18]
I've tried to download and install from the AssetLib, and it crashes every time. I have Godot in compatibility mode.

I have also tried to download and manually add to addons folder to no avail. The files to not show up in Godot, though they are actually in the folder (I can see them in file manager).

I'm on a mac.

**Comment by Adriankhl** [comment]
By any chance you are using an intel x86 mac?

**Comment by Mixddux** [comment]
I was able to get this up and running on Windows, so I will close this ticket until I get more familiar with it. I think it's my lack of experience that's the problem.

Thank you for the responsive reply.

**Comment by Mixddux** [comment]
Switched over to Windows and it seems to work. Closing this because I'm dumb.
