### ISSUE TITLE
Problems in running the plugin

### ISSUE THREAD

**Issue by JekSun97** [Adriankhl/godot-llm#2]
Please add SCons to build

**Comment by Adriankhl** [comment]
I would love to add a scons build, however, the [llama.cpp](https://github.com/ggerganov/llama.cpp/tree/a8f9b076316e16aadd0791015b3bfd446fe1e904) dependency is a CMake/Make project and I believe it is quite hacky to integrate scons with CMake/Make.

It is possible to port a scons build for [llama.cpp](https://github.com/ggerganov/llama.cpp/tree/a8f9b076316e16aadd0791015b3bfd446fe1e904). It is a major effort though.

**Comment by JekSun97** [comment]
@Adriankhl I built it using CMake, I now have the libraries godot-cpp.windows.debug.32.lib, libgodot_llm.windows..amd64.lib, llama.lib, ggml_static.lib, what should I do with all this next?

**Comment by Adriankhl** [comment]
@JekSun97 I am not familiar with visual studio myself, but it seems like you are getting close.

You need to find a way to build a dynamic library `dll` instead of static library `lib`, and if possible, set the cmake variable a `CMAKE_BUILD_TYPE` to `Release` (be aware that this is not used by MSBuild, you need to set the release build target somewhere else). Then, you should be able to build `libgodot_llm.windows.release.amd64.dll` (or rename the `libgodot_llm...` to this if you don't know how to set the cmake variable)


Finally, simply copy the dll and gdextension file to the addons folder of your godot project

```
├── addons
│   └── godot_llm
│       ├── bin
                        libgodot_llm.windows.release.amd64.dll
│       └── godot_llm.gdextension
```

**Comment by JekSun97** [comment]
It turns out that initially there was a compilation type for dll, now I decided to build libgodot_llm.windows..amd64 separately, but I get errors:

godot-cpp.windows.debug.32.lib(node.obj) : error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": value "2" does not match value "0" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(node.obj) : error LNK2038: mismatch detected for "RuntimeLibrary": value "MDd_DynamicDebug" does not match value "MD_DynamicRelease" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(wrapped.obj) : error LNK2038: Inconsistency detected for "_ITERATOR_DEBUG_LEVEL": value "2" does not match value "0" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(wrapped.obj) : error LNK2038: Inconsistency detected for "RuntimeLibrary": value "MDd_DynamicDebug" does not match value "MD_DynamicRelease" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(error_macros.obj) : error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": value "2" does not match value "0" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(error_macros.obj) : error LNK2038: mismatch detected for "RuntimeLibrary": value "MDd_DynamicDebug" does not match value "MD_DynamicRelease" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(memory.obj) : error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": value "2" does not match value "0" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(memory.obj) : error LNK2038: mismatch detected for "RuntimeLibrary": value "MDd_DynamicDebug" does not match value "MD_DynamicRelease" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(char_string.obj) : error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": value "2" does not match value "0" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(char_string.obj) : error LNK2038: mismatch detected for "RuntimeLibrary": value "MDd_DynamicDebug" does not match value "MD_DynamicRelease" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(string.obj) : error LNK2038: Inconsistency detected for "_ITERATOR_DEBUG_LEVEL": value "2" does not match value "0" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(string.obj) : error LNK2038: mismatch detected for "RuntimeLibrary": value "MDd_DynamicDebug" does not match value "MD_DynamicRelease" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(string_name.obj) : error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": value "2" does not match value "0" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(string_name.obj) : error LNK2038: mismatch detected for "RuntimeLibrary": value "MDd_DynamicDebug" does not match value "MD_DynamicRelease" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(variant.obj) : error LNK2038: Inconsistency detected for "_ITERATOR_DEBUG_LEVEL": value "2" does not match value "0" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(variant.obj) : error LNK2038: Inconsistency detected for "RuntimeLibrary": value "MDd_DynamicDebug" does not match value "MD_DynamicRelease" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(object.cpp.obj) : error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": value "2" does not match value "0" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(object.cpp.obj) : error LNK2038: mismatch detected for "RuntimeLibrary": value "MDd_DynamicDebug" does not match value "MD_DynamicRelease" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(method_bind.obj) : error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": value "2" does not match value "0" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(method_bind.obj) : error LNK2038: mismatch detected for "RuntimeLibrary": value "MDd_DynamicDebug" does not match value "MD_DynamicRelease" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(class_db.obj) : error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": value "2" does not match value "0" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(class_db.obj) : error LNK2038: mismatch detected for "RuntimeLibrary": value "MDd_DynamicDebug" does not match value "MD_DynamicRelease" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(godot.obj) : error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": value "2" does not match value "0" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(godot.obj) : error LNK2038: mismatch detected for "RuntimeLibrary": value "MDd_DynamicDebug" does not match value "MD_DynamicRelease" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(resource.obj) : error LNK2038: Inconsistency detected for "_ITERATOR_DEBUG_LEVEL": value "2" does not match value "0" in gdllama.obj
1>godot-cpp.windows.debug.32.lib(resource.obj) : error LNK2038: mismatch detected for "RuntimeLibrary": value "MDd_DynamicDebug" does not match value "MD_D"

**Comment by JekSun97** [comment]
I decided not to suffer and download the finished build, fortunately the license allows me to do this, once I test it I’ll post :)

**Comment by Adriankhl** [comment]
You are mixing debug build and release build, probably need to clean up project and rebuild everything under the same mode

**Comment by JekSun97** [comment]
@Adriankhl  I installed the plugin manually and via AssetLib, and I get the same error:
![22](https://github.com/Adriankhl/godot-llm/assets/130399274/50d09a82-7da4-433f-91b7-d6e9b70895ad)

**Comment by Adriankhl** [comment]
> @Adriankhl I installed the plugin manually and via AssetLib, and I get the same error: ![22](https://private-user-images.githubusercontent.com/130399274/327194070-50d09a82-7da4-433f-91b7-d6e9b70895ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MDczOTQsIm5iZiI6MTcxNDYwNzA5NCwicGF0aCI6Ii8xMzAzOTkyNzQvMzI3MTk0MDcwLTUwZDA5YTgyLTdkYTQtNDMzZi05MWI3LWQ2ZTliNzA4OTVhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQyMzQ0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWYyZmNhOGZkYjBhMDc4M2Q4MTUwYWJlYjQ3MTUxYjFiNDY2NDk1ZTI5MjJmZDgxYjc5MmFmNDU5MTI1YThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XtTnWajJulF5kKEVswQA6wvIYmttjcsHwPM3cE5EK7g)

May I confirm that you have created a new project, installed the plugin from the asset library, and this error pops up?

**Comment by Adriankhl** [comment]
If that is the case can you try to extract the dll file here and replace the `addons/godot_llm/bin/libgodot_llm.windows.release.amd64.dll` by this new file?
[libgodot_lib.zip](https://github.com/Adriankhl/godot-llm/files/15182473/libgodot_lib.zip)

**Comment by JekSun97** [comment]
> >
> May I confirm that you have created a new project, installed the plugin from the asset library, and this error pops up?

Yes

> If that is the case can you try to extract the dll file here and replace the `addons/godot_llm/bin/libgodot_llm.windows.release.amd64.dll` by this new file? [libgodot_lib.zip](https://github.com/Adriankhl/godot-llm/files/15182473/libgodot_lib.zip)
> 
> This is built without vulkan acceleration, just to see if the problem is related to gpu settings

Same error :(

**Comment by Adriankhl** [comment]
:( Do you have Microsoft Visual C++ Redistributable installed?

**Comment by Adriankhl** [comment]
Let's try it one more time, here I also statically linked MSVC runtime.
[libgodot_llm.zip](https://github.com/Adriankhl/godot-llm/files/15183395/libgodot_llm.zip)

**Comment by spiderbyte87** [comment]
Installing the addon crashes the editor for me.

**Comment by Adriankhl** [comment]
> Installing the addon crashes the editor for me.

May I know if you have [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) installed?

**Comment by Adriankhl** [comment]
I have created a new version of the plugin, this time I statically link the library to msvc runtime so no dependencies are needed, hopefully it fixes the problem.

**Comment by spiderbyte87** [comment]
> > Installing the addon crashes the editor for me.
> 
> May I know if you have [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) installed?

I don't have MSVC. I tried the new version and it's still crashing as soon as the editor starts. I'm on Linux.. should I drop into Windows to see it the problem persists or would that not be it?

**Comment by Adriankhl** [comment]
> > > Installing the addon crashes the editor for me.
> > 
> > 
> > May I know if you have [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) installed?
> 
> I don't have MSVC. I tried the new version and it's still crashing as soon as the editor starts. I'm on Linux.. should I drop into Windows to see it the problem persists or would that not be it?

I see. It is strange that I am able to reproduce the problem on my linux laptop but it works fine under wsl on Windows, let me spend some time today to investigate the problem.

**Comment by JekSun97** [comment]
> :( Do you have Microsoft Visual C++ Redistributable installed?

Yes


> Let's try it one more time, here I also statically linked MSVC runtime. [libgodot_llm.zip](https://github.com/Adriankhl/godot-llm/files/15183537/libgodot_llm.zip)

![322](https://github.com/Adriankhl/godot-llm/assets/130399274/fa233703-567c-41f8-9cc7-53e5f3d38464)

**Comment by Adriankhl** [comment]
@JekSun97 @spiderbyte87 Finally I know what happened, there is a hidden default `LLAMA_NATIVE` option in the `llama.cpp` build, which introduces optimization to my local cpu, but it becomes incompatible on many platform. The Windows problem and Linux problem are the same issue, just that Windows handle the incompatibility slightly better so it doesn't crash (though it still doesn't provide useful debug information. 


I have tested the new version on multiple PCs and VMs, I think now it should work.

**Comment by spiderbyte87** [comment]
> @JekSun97 @spiderbyte87 Finally I know what happened, there is a hidden default `LLAMA_NATIVE` option in the `llama.cpp` cmake build, which introduces optimization for my local cpu, but the binary becomes incompatible on many platforms. The Windows problem and Linux problem are the same issue, just that Windows handle the incompatibility slightly better so it doesn't crash (though it still doesn't provide useful debug information).
> 
> I have disabled the option and tested the new version on multiple PCs and VMs, I think now it should work.

Will give it a try a little later today and let you know it if it works!

**Comment by spiderbyte87** [comment]
Yep it works without a hitch. I would highly recommend packaging this as a proper Godot addon with all the components in one place. Other than that, it's pretty great! I spent all yesterday getting Ollama working via POST, which works fine, but this is a far better solution! Thanks again!!

**Comment by JekSun97** [comment]
@Adriankhl can I test the dll?

**Comment by Adriankhl** [comment]
> @Adriankhl can I test the dll?

Yes, you can grep it from the the zip file of the release page: https://github.com/Adriankhl/godot-llm/releases/tag/v0.2.2

You will fine `libgodot_llm.windows.release.amd64.dll` in the `bin` folder

**Comment by JekSun97** [comment]
Now there is no error, but for some reason I couldn’t wait for an answer, I waited for about an hour, then closed the application.

I used this code:
```
extends Node

var lm = GDLlama.new()

func _ready() -> void:
if FileAccess.file_exists("res://Meta-Llama-3-8B-Instruct-Q5_K_M.gguf"):
lm.model_path="res://Meta-Llama-3-8B-Instruct-Q5_K_M.gguf"
var gen = lm.generate_text("5+5?")
print(gen)
else:
print("no file!")
pass
```

**Comment by Adriankhl** [comment]
> var gen = lm.generate_text("5+5?")

The default llama.cpp parameter `lm.n_predict = -1` generates an infinite sequence, try setting `lm.n_predict = 10` before running `lm.generate_text`

**Comment by JekSun97** [comment]
@Adriankhl  Thank you! Now everything is working, I advise you to write the minimum verification code in the README for a quick start.

I wanted to know how you can make it so that the model can receive and respond in other languages? Maybe some special model is needed?

**Comment by Adriankhl** [comment]
> @Adriankhl Thank you! Now everything is working, I advise you to write the minimum verification code in the README for a quick start.

Thanks for the suggestion! There is already a template godot project as a starting, but I think it is also good to have some simple coding example in the README.

> I wanted to know how you can make it so that the model can receive and respond in other languages? Maybe some special model is needed?

It really depends on the model, llama 3 is already multillingual (depends on which language you want, it may or may not be good), and there are fine-tuned models which strengthen the output in a particular language. Bear in mind that the current stable version of this plugin doesn't convert utf8 correctly (fixed in the development version), so characters in other languages might be garbled.

**Comment by Adriankhl** [comment]
@JekSun97 I have fixed the text encoding bug, now at least llama 3 works in Chinese according to my testing.

And I have also updated the README documentation, I hope now it is clear enough 😺

**Comment by JekSun97** [comment]
> @JekSun97 I have fixed the text encoding bug, now at least llama 3 works in Chinese according to my testing.
> 
> And I have also updated the README documentation, I hope now it is clear enough 😺

Best! I'll test it today

**Comment by Adriankhl** [comment]
Let's close this and use a new issue thread if there are further problems
