### ISSUE TITLE
GPT4All? 

### ISSUE THREAD

**Issue by JekSun97** [Adriankhl/godot-llm#3]
Are you considering adding models like GPT4All?

As far as I understand, it is similar to a llama, with the exception that the behavior of the model and its response patterns can be customized, it also works locally.

**Comment by Adriankhl** [comment]
😄 Actually, I didn't have time to look into this yet, but I believe GPT4All is a spin-off from llama.cpp which offer the similar features. I will consider other types of backend after completing llama.cpp embedding and llava features (which is pretty soon!)
