### ISSUE TITLE
How to get it to exclude the prompt in the output

### ISSUE THREAD

**Issue by spiderbyte87** [Adriankhl/godot-llm#4]
I've been banging my head against the wall trying to pull only the generated text without the prompt. I can get a debug print with only the prompt by being tricky with strings, but that's messy.

**Comment by Adriankhl** [comment]
Do you have the patient to wait a few more hours to a day 😄 A new release is coming which adds an option to disable prompt output (and a lot more functionalities!) I just need to write up the documentation and do a bit of testing.

**Comment by spiderbyte87** [comment]
Dang dude you're on it! That's freaking awesome!!

**Comment by Adriankhl** [comment]
The new version is out, waiting for the asset library to approve the release, or you may just get it from the github release page. Now, you can simply turn off the `Should Output Prompt` property (in GDScript `should_output_prompt = false`) to disable outputting the input prompt. You can also turn off `Should Output Bos` and `Should Output Eos` to disable those beginning and ending token.

**Comment by spiderbyte87** [comment]
> The new version is out, waiting for the asset library to approve the release, or you may just get it from the github release page. Now, you can simply turn off the `Should Output Prompt` property (in GDScript `should_output_prompt = false`) to disable outputting the input prompt. You can also turn off `Should Output Bos` and `Should Output Eos` to disable those beginning and ending token.

I literally just downloaded it and I'm testing inow. Will let you know if I run into any issues.

**Comment by spiderbyte87** [comment]
Only issue was I was running a script to do multithreading manually, but it looks like you included proper threading in the extension for this version, causing it to freeze when trying to generate text while a thread was already running. Deleted my script and set it to run directly using the class functions and everything works great. Here's a clip of how I'm using your plugin:
[](https://youtu.be/iW7Bom5qbPI)

Thanks again for all your hard work! I'll be including (with your permission) your info in the credits when my game releases!!

**Comment by Adriankhl** [comment]
> Only issue was I was running a script to do multithreading manually, but it looks like you included proper threading in the extension for this version, causing it to freeze when trying to generate text while a thread was already running. Deleted my script and set it to run directly using the class functions and everything works great. Here's a clip of how I'm using your plugin: https://youtu.be/iW7Bom5qbPI
> 
> Thanks again for all your hard work! I'll be including (with your permission) your info in the credits when my game releases!!

Very cool! Wish you have a successful release.

**Comment by Adriankhl** [comment]
> Only issue was I was running a script to do multithreading manually, but it looks like you included proper threading in the extension for this version, causing it to freeze when trying to generate text while a thread was already running

Yes, threading is hard, especially with signals and big ram usage for LLM. Instead of using things like callback to handle parallel execution, I decided to keep it simple - only one execution per node, and it freezes easily to ensure that people notice the mistake when they call a function while the background thread is already running. You can always duplicate the node to execute things in parallel.
