### ISSUE TITLE
`run_generate_text` doesn't trigger `generate_text_finished`

### ISSUE THREAD

**Issue by JanWerder** [Adriankhl/godot-llm#9]
For a sample project please see https://github.com/Adriankhl/godot-llm/issues/8

It seems like even though `generate_text_updated` is triggered, `generate_text_finished` is not triggered when using `run_generate_text`.

**Comment by Adriankhl** [comment]
In your sample, you have `Interactive` mode on. And this is the current design of the plugin - if this is interactive and when the model pause in the middle to wait for more input, `input_wait_started` signal is emitted, only after the whole conversation is over, i.e., you stop the interaction by calling `stop_generate_text`, the `generate_text_finished` will be triggered. 

You just need to turn off the `Interactive` property (and fix the missing argument `func _run_2(text):`) and it should work.

Let me know if you have a different opinion on the current design though.

**Comment by JanWerder** [comment]
Ah ok, no you're right. That's fine and it's even part of the documentation under signals. My miss.
I think it would be good in the API docs at some point.
